<a href="https://colab.research.google.com/github/Khushi232505/AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Welcome to numpy tutorial..***

In [ ]:
pip install numpy

In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


#***Execution Performance***

In [5]:
size = 10_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#np arrays
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_arr**2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 2.4644358158111572 seconds
numpy array time = 0.05719399452209473 seconds


In [6]:
# memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


#***Create numpy array from list***

In [7]:
# create - from lists

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2-Dimensional array
arr2D = np.array([[1,2,3], [5,6,7], [8,9,10], [10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 12]] (4, 3)


#***Using built-in Functions***


In [8]:
arr1 =np.zeros((2,3), dtype = "int64") #prefill with 0
print(arr1, arr1.shape)

arr2 =np.ones((5,4), dtype = "int64") #prefill with 1
print(arr2, arr2.shape)

arr3 =np.full((3,4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 =np.eye((3), dtype = "int64") # identity matrix
print(arr4, arr4.shape)

#range(start, end, step)
arr5 =np.arange(0, 11, 2) # range elements
print(arr5, arr5.shape)

#(start,stop,num)
arr6 =np.linspace(1, 100, 6) #evenly spaced array
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (5, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   20.8  40.6  60.4  80.2 100. ] (6,)
