<a href="https://colab.research.google.com/github/Khushi232505/AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Welcome to numpy tutorial..***

In [3]:
pip install numpy

In [4]:
import numpy as np
import time

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


#***Execution Performance***

In [ ]:
size = 10_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#np arrays
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_arr**2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 2.4644358158111572 seconds
numpy array time = 0.05719399452209473 seconds


In [ ]:
# memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


#***Create numpy array from list***

In [ ]:
# create - from lists

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2-Dimensional array
arr2D = np.array([[1,2,3], [5,6,7], [8,9,10], [10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 12]] (4, 3)


#***Using built-in Functions***


In [ ]:
arr1 =np.zeros((2,3), dtype = "int64") #prefill with 0
print(arr1, arr1.shape)

arr2 =np.ones((5,4), dtype = "int64") #prefill with 1
print(arr2, arr2.shape)

arr3 =np.full((3,4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 =np.eye((3), dtype = "int64") # identity matrix
print(arr4, arr4.shape)

#range(start, end, step)
arr5 =np.arange(0, 11, 2) # range elements
print(arr5, arr5.shape)

#(start,stop,num)
arr6 =np.linspace(1, 100, 6) #evenly spaced array
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (5, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   20.8  40.6  60.4  80.2 100. ] (6,)


#***Properties***

In [ ]:
# properties

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape) #dimension = m x n
print(arr.size) #total elements = 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


#***Operations on array***

In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened  = arr.flatten() #2D --> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [19]:
# Indexing
# arr = np.array([1, 2, 3, 4, 5])
# print(arr[0])
# print(arr[4])

arr  = np.array([[1,2,3],[4,5,6]])
print(arr[1,1])
print(arr[0][2])

#Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])
idx = [0,1,3]
print(arr[idx])

#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr>2])
print(arr[arr%2 ==0 ])

5
3
[1 2 4]
[3 4 5]
[2 4]


In [22]:
# Slicing
arr = np.array([1, 2, 3, 4, 5]) #[start, end, step]

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [30]:
#Copy VS View

# nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)/

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0]= 200
print(sub_arr)
print(arr)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0]= 200
print(sub_arr)
print(arr)


[2 3]
[200   3]
[  1 200   3   4   5]
[2 3]
[200   3]
[1 2 3 4 5]
