<a href="https://colab.research.google.com/github/Khushi232505/AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Welcome to numpy tutorial..***

In [2]:
pip install numpy

In [1]:
import numpy as np
import time

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


#***Execution Performance***

In [ ]:
size = 10_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#np arrays
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_arr**2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 2.4644358158111572 seconds
numpy array time = 0.05719399452209473 seconds


In [ ]:
# memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


#***Create numpy array from list***

In [ ]:
# create - from lists

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2-Dimensional array
arr2D = np.array([[1,2,3], [5,6,7], [8,9,10], [10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 12]] (4, 3)


#***Using built-in Functions***


In [ ]:
arr1 =np.zeros((2,3), dtype = "int64") #prefill with 0
print(arr1, arr1.shape)

arr2 =np.ones((5,4), dtype = "int64") #prefill with 1
print(arr2, arr2.shape)

arr3 =np.full((3,4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 =np.eye((3), dtype = "int64") # identity matrix
print(arr4, arr4.shape)

#range(start, end, step)
arr5 =np.arange(0, 11, 2) # range elements
print(arr5, arr5.shape)

#(start,stop,num)
arr6 =np.linspace(1, 100, 6) #evenly spaced array
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (5, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   20.8  40.6  60.4  80.2 100. ] (6,)


#***Properties***

In [ ]:
# properties

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape) #dimension = m x n
print(arr.size) #total elements = 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


#***Operations on array***

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened  = arr.flatten() #2D --> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
# Indexing
# arr = np.array([1, 2, 3, 4, 5])
# print(arr[0])
# print(arr[4])

arr  = np.array([[1,2,3],[4,5,6]])
print(arr[1,1])
print(arr[0][2])

#Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])
idx = [0,1,3]
print(arr[idx])

#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr>2])
print(arr[arr%2 ==0 ])

5
3
[1 2 4]
[3 4 5]
[2 4]


In [ ]:
# Slicing
arr = np.array([1, 2, 3, 4, 5]) #[start, end, step]

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [ ]:
#Copy VS View

# nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)/

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0]= 200
print(sub_arr)
print(arr)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0]= 200
print(sub_arr)
print(arr)


[2 3]
[200   3]
[  1 200   3   4   5]
[2 3]
[200   3]
[1 2 3 4 5]


#***Data Types***

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3.9, 4, 5])
arr3 = np.array([1, 2, 3.9, 4, 5,"prime"])
arr4 = np.array([1, 5+8j])
arr5 = np.array(["prime", {1,2,3}, 3.14])

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)
print(arr4, arr4.dtype)
print(arr5, arr5.dtype)

[1 2 3 4 5] int64
[1.  2.  3.9 4.  5. ] float64
['1' '2' '3.9' '4' '5' 'prime'] <U32
[1.+0.j 5.+8.j] complex128
['prime' {1, 2, 3} 3.14] object


#***Multi-Dimensional Array***

In [ ]:
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_col = np.sum(arr2D, axis=0)
print(sum_of_col)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

print(arr2D[0:2, 1:2]) #slicing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


#***3D Array***

In [ ]:
arr3D = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]]) #2x 3x2
print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

#slicing
print(arr3D[:, 0, :]) #first row from both layers
print(arr3D[:, :, 0]) #first column from both layers

#manipulate the data
arr3D[:, 0, :] = 0 #change first row to store 0.
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[ 0  0]
  [ 3  4]
  [ 5  6]]

 [[ 0  0]
  [ 9 10]
  [11 12]]]


#***Vectorization***

In [7]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr**2)
print(arr + 2)
print(arr + arr2)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 7  9 11 13 15]


#***Broadcasting***

In [10]:
arr = np.array([1,2,3,4,5])
print(arr+5 )

arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr + arr2)

print(arr.shape)
print(arr2.shape)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(5,)
(2, 5)


#***Normailization***

In [15]:
arr = np.array([[1,2],[3,4]])


mean = np.mean(arr)
std_dev = np.std(arr)

print(mean)
print(std_dev)

normailzed_arr = (arr-mean)/std_dev
print(normailzed_arr)


2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


#***Mathematical functions***

In [30]:
# aggregation

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [31]:
# power functions

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [35]:
# log functions

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [45]:
# rounding functions

print(np.round(3.14))
print(np.ceil(3.02))
print(np.floor(3.99))
print(np.trunc(3.14))

arr = np.array([-6,1, 2,-8, 10, 2, 3, 4, 5])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-8 -6  1  2  3  4  5 10]
[-8 -6  1  2  2  3  4  5 10]
[ 6  1  2  8 10  2  3  4  5]
